version: '3.7'

networks:
  traefik:
    external: true

services:

  front:
    build: .
    restart: unless-stopped
    ports:
      - 80
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=fantus'
      - 'traefik.docker.network=traefik'
      - 'traefik.frontend.rule=Host:fantus.studio'
      - 'traefik.port=80'
  
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .directus
    ports:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql

  directus:
    image: directus/directus:v8-apache
    restart: unless-stopped
    env_file: .directus
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.backend=fantus-api"
      - "traefik.frontend.rule=Host:api.fantus.studio"
